source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '10.0'
use_frameworks!

def shared_Timer_Weather
    pod 'RxSwift'
    pod 'ObjectMapper'
end

target "Timer-Weather" do
    shared_Timer_Weather
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'SwiftIcons'
    pod 'HGCircularSlider'
    pod 'SwiftGen'
end

target "Timer-WeatherTests" do
    shared_Timer_Weather
end
