source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '10.0'
use_frameworks!

target "Timer-Weather" do
    pod 'Alamofire'
    pod 'SwiftIcons'
    pod 'HGCircularSlider'
    pod 'SwiftGen'
end

target "Timer-WeatherTests" do
end
